after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = "qwerty"

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

[mode.main.binding]
alt-comma = "layout horizontal vertical"
alt-slash = "layout tiles accordion"
alt-f = "fullscreen"
alt-shift-c = "reload-config"
alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"
alt-shift-h = "move left --boundaries-action fail"
alt-shift-j = "move down --boundaries-action fail"
alt-shift-k = "move up --boundaries-action fail"
alt-shift-l = "move right --boundaries-action fail"
alt-minus = "resize smart -50"
alt-equal = "resize smart +50"
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"
alt-6 = "workspace 6"
alt-7 = "workspace 7"
alt-8 = "workspace 8"
alt-9 = "workspace 9"
# alt-y = "workspace 1"
# alt-u = "workspace 2"
# alt-i = "workspace 3"
# alt-o = "workspace 4"
# alt-p = "workspace 5"
alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-4 = "move-node-to-workspace 4"
alt-shift-5 = "move-node-to-workspace 5"
alt-shift-6 = "move-node-to-workspace 6"
alt-shift-7 = "move-node-to-workspace 7"
alt-shift-8 = "move-node-to-workspace 8"
alt-shift-9 = "move-node-to-workspace 9"
# alt-shift-y = "move-node-to-workspace 1"
# alt-shift-u = "move-node-to-workspace 2"
# alt-shift-i = "move-node-to-workspace 3"
# alt-shift-o = "move-node-to-workspace 4"
# alt-shift-p = "move-node-to-workspace 5"
# alt-tab = 'workspace-back-and-forth'
# alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-f = "layout floating tiling"
alt-semicolon = "mode join-with"
alt-r = "mode resize"
alt-e = "mode swap-workspaces"

[mode.resize.binding]
enter = "mode main"
esc = "mode main"
alt-shift-f = "layout floating tiling"
alt-semicolon = "mode join-with"
alt-r = "mode main"
alt-e = "mode swap-workspaces"
alt-comma = "layout horizontal vertical"
alt-slash = "layout tiles accordion"
alt-f = "fullscreen"
alt-shift-c = "reload-config"
b = "balance-sizes"
h = "resize width -50"
j = "resize height +50"
k = "resize height -50"
l = "resize width +50"
alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"
alt-shift-h = "move left --boundaries-action fail"
alt-shift-j = "move down --boundaries-action fail"
alt-shift-k = "move up --boundaries-action fail"
alt-shift-l = "move right --boundaries-action fail"

[mode.join-with.binding]
enter = "mode main"
esc = "mode main"
alt-shift-f = "layout floating tiling"
alt-semicolon = "mode main"
alt-r = "mode resize"
alt-e = "mode swap-workspaces"
alt-comma = "layout horizontal vertical"
alt-slash = "layout tiles accordion"
alt-f = "fullscreen"
alt-shift-c = "reload-config"
f = "flatten-workspace-tree"
h = "join-with left"
j = "join-with down"
k = "join-with up"
l = "join-with right"
alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"
alt-shift-h = "move left --boundaries-action fail"
alt-shift-j = "move down --boundaries-action fail"
alt-shift-k = "move up --boundaries-action fail"
alt-shift-l = "move right --boundaries-action fail"

[mode.swap-workspaces.binding]
enter = "mode main"
esc = "mode main"
alt-semicolon = "mode join-with"
alt-r = "mode resize"
alt-e = "mode main"
1 = [
  "exec-and-forget /Users/main/.config/aerospace/swap-workspaces.sh 1",
  "mode main",
]
2 = [
  "exec-and-forget /Users/main/.config/aerospace/swap-workspaces.sh 2",
  "mode main",
]
3 = [
  "exec-and-forget /Users/main/.config/aerospace/swap-workspaces.sh 3",
  "mode main",
]
4 = [
  "exec-and-forget /Users/main/.config/aerospace/swap-workspaces.sh 4",
  "mode main",
]
5 = [
  "exec-and-forget /Users/main/.config/aerospace/swap-workspaces.sh 5",
  "mode main",
]
6 = [
  "exec-and-forget /Users/main/.config/aerospace/swap-workspaces.sh 6",
  "mode main",
]
7 = [
  "exec-and-forget /Users/main/.config/aerospace/swap-workspaces.sh 7",
  "mode main",
]
8 = [
  "exec-and-forget /Users/main/.config/aerospace/swap-workspaces.sh 8",
  "mode main",
]
9 = [
  "exec-and-forget /Users/main/.config/aerospace/swap-workspaces.sh 9",
  "mode main",
]
