# "$schema" = "https://starship.rs/config-schema.json"

format = "$directory $git_branch $git_status $character"
add_newline = false

[directory]
format = "[$path]($style)"
style = "blue"
use_logical_path = true
# truncate_to_repo = true
# truncation_length = 0

[git_branch]
format = "[$branch]($style)"
style = "green"

[git_status]
format = "[$all_status$ahead_behind]($style)"
conflicted = "="
ahead = "^"
behind = "v"
diverged = "^v"
up_to_date = ""
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = ">"
deleted = "x"
typechanged = ""

[character]
disabled = true
# success_symbol = "❯"
# error_symbol = "❯"
